baseURL = 'https://blog.eduardoborges.dev'
languageCode = 'pt-BR'
title = 'edu blog'
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5 # articles per page

[params]
mode="toggle" # color-mode → light,dark,toggle or auto
subtitle = "o blogzinho do edu. as vezes coisas úteis, as vezes besteirol. vou tentar escrever coisas relevantes sobre javascript."
favicon = "https://eduardoborges.dev/favicon.png"


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/eduardoborges"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/euduardoborges"

[[params.social]]
name = "Linkedin"
icon = "music"
url = "https://spotify.com"


# Main menu Items

[[menu.main]]
name = "publicaçoes"
url = "/posts"