baseURL = 'https://blog.eduardoborges.dev'
languageCode = 'pt-br'
theme = "archie"
title = 'Edu Blog'
copyright = "© Eduardo Borges"


paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/eduardoborges"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "GitHub"
icon = "github"
url = "https://twitter.com/dudao_borges"
weight = 3