baseURL = 'https://eduardoborges.dev'
languageCode = 'pt-BR'
title = 'eduardo borges'

pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5

[params]
favicon = "/favicon.png"

# Main menu Items

[[menu.main]]
name = "posts"
url = "/posts"

[[menu.main]]
name = "tags"
url = "/tags"