baseURL = 'https://blog.eduardoborges.dev'
languageCode = 'pt-BR'
title = 'edu blog'
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5 # articles per page

[params]
mode="toggle" # color-mode → light,dark,toggle or auto
subtitle = "o blogzinho do edu. as vezes coisas úteis, as vezes besteirol. vou tentar escrever coisas relevantes sobre javascript."
favicon = "https://eduardoborges.dev/favicon.png"


# Main menu Items

[[menu.main]]
name = "home"
url = "/"

[[menu.main]]
name = "posts"
url = "/posts"

[[menu.main]]
name = "tags"
url = "/tags"