name: Deploy
on:
  workflow_dispatch:
  push:
    branches: ["main"]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PUPPETEER_EXEC_PATH: "/usr/bin/chromium"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Chromium and Hugo
        run: sudo snap install chromium hugo

      - name: Install Deps
        run: npm ci

      - name: Build
        run: npm run build


      - name: Deploy to CloudFlare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          command: |
            pages deploy ./dist --project-name=blog --branch=main
  
