# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy & Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.105.0'
          
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '18.x'
          
      - uses: actions/checkout@v3

      - run: npm run build
        
      - uses: actions/upload-artifact@v3
        with:
          name: blog-build
          path: dist
    
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
    steps:
      - uses: actions/setup-node@v3.5.1

      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: blog-build

      - run: ls -la

      - run: |
          npm install -g wrangler 
          npx wrangler pages deployment create dist --project-name=blog



  
  
