name: Deploy
on:
  workflow_dispatch:
  push:
    branches: ["main"]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PUPPETEER_EXEC_PATH: "/usr/bin/chromium"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
      - run: sudo snap install chromium
      - run: sudo snap install hugo
      - run: npm i -g zx
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: blog-build
          path: dist
    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
    steps:
      - uses: actions/setup-node@v3.5.1
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: blog-build
      - run: ls -la
      - run: |
          npm install -g wrangler 
          npx wrangler pages deployment create . --project-name=blog



  
  
