# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy & Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.105.0'
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '18.x'
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with Hugo
        run: npm run build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
  
